package exceptionPackage;

public enum DataFetchExceptionTypes {
    CLOSE_EXCEPTION,
    TIMEOUT_EXCEPTION,
    CONNECTION_EXCEPTION,
    PREPARED_STATEMENT_EXCEPTION,
    RESULT_SET_EXCEPTION,
    RESULT_EMPTY

}
